# Change these first
owner: infinity-loopA-Z # Your GitHub organization or username, where this repository lives
repo: super-octo-waddle # The name of this repository

sites:
  - name: Bigbox Argentina
    url: https://www.bigbox.com.ar
  - name: Biglife Argentina
    url: https://www.premios.bigbox.com.ar
